[package]
name = "manta-compare"
version = "0.4.0"
description = "A cross-platform file, folder and git diff comparison tool"
authors = ["marrviin"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This can be commented out or removed if you don't need to use the library from an external application.
name = "manta_compare_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding_rs = "0.8"
chardetng = "0.1"
content_inspector = "0.2"
trash = "5"
tauri-plugin-fs = "2.5.2"
tauri-plugin-store = "2.4.4"
tauri-plugin-os = "2"
url = "2"
